behavior_variable


PerfectTrials = videocod.ValidVideo==1 & ...
                videocod.DoesTheTask==1 & ...
                videocod.Success==1 & ...
                videocod.MoveTowardTarget==1 & ...
                videocod.RakePulled==1 & ...
                videocod.Groove_graspPriority==1 &...
                videocod.MultipleAttempts==0 & ...
                videocod.PlaceTarget==0 & ...
                videocod.ShaftCorrection==0 & ...
                videocod.MissTarget==0 & ...
                videocod.HitTarget==0 & ...
                videocod.Volte==0 & ...
                ~strcmp(videocod2.RakeStarting,'17');

ValidTrials = videocod.ValidVideo==1 & ...
              videocod.DoesTheTask==1 & ...
              videocod.ValidVideo==1 & ...
              videocod.ValidVideo==1 & ...
              videocod.ValidVideo==1 & ...
              videocod.ValidVideo==1 & ...
              videocod.ValidVideo==1 