%code the Success after a failure if the parameter are the same (same rake
%and target starting). Check if the trial before is a failure in the same
%condition and the trial after a success in the same condition. Check also
%if the one with success is with multiple attempts and if after this one
%there is a success in the same condition without multiple attempts.and take
%into consideration the possible invalid trials between a failure and a success. 



subject= 'Samovar';
coder= 'SK'; % ND = Noémie Dessaint, SK = Sébastien Kirchherr, GC = Gino Coudé
stage=1;

%dates={'01.07.19','02.07.19','03.07.19','04.07.19','05.07.19','08.07.19','11.07.19','12.07.19','15.07.19'};
%dates={'07.05.19','09.05.19','14.05.19','16.05.19','17.05.19','20.05.19','21.05.19','22.05.19'};
%dates={'04.10.19','07.10.19','08.10.19','09.10.19','10.10.19','11.10.19','14.10.19','16.10.19','17.10.19','18.10.19',};

dates={'11.06.21','15.06.21','16.06.21','17.06.21','18.06.21','22.06.21','23.06.21','08.07.21','09.07.21','13.07.21','14.07.21',...
    '15.07.21','04.08.21','10.08.21','11.08.21','12.08.21','13.08.21','17.08.21','18.08.21','19.08.21','20.08.21',...
    '24.08.21','25.08.21','02.09.21','03.09.21','07.09.21','11.10.21','12.10.21','13.10.21','14.10.21','26.10.21','27.10.21','28.10.21',...
    '29.10.21','02.11.21','03.11.21'};
    

days_nbr=length(dates);

output_path=fullfile('E:\project\video_coding\', subject,'table');

Behavior=table('Size',[days_nbr 42],'VariableTypes',{'string','double','double',...
    'double','double','double','double','double','double','double','double','double','double','double',...
    'double','double','double','double','double','double','double','double','double','double','double','double',...
    'double','double','double','double','double','double','double','double','double','double','double','double','double',...
    'double','double','double'});
Behavior.Properties.VariableNames={'date','ValidTrial','Left','Center','Right','Success nbr','Success','Thirds',...
    'Modulo','SuccessSessionStart_nbr','SuccessSessionMiddle_nbr','SuccessSessionEnd_nbr','SuccessSessionStart',...
    'SuccessSessionMiddle','SuccessSessionEnd','DaySuccessSessionStart','DaySuccessSessionMiddle','DaySuccessSessionEnd',...
    'SuccessLeft_nbr','SuccessLeft','SuccessCenter_nbr','SuccessCenter','SuccessRight_nbr','SuccessRight','DaySuccessLeft',...
    'DaySuccessCenter','DaySuccessRight','SuccessAligned_nbr','SuccessAligned','DaySuccessAligned','SuccessR2L_nbr',...
    'SuccessR2L','DaySuccessR2L','SuccessL2R_nbr','SuccessL2R','DaySuccessL2R','MultipleAttempt_nbr',...
    'SuccessMultipleAttempt_nbr','SuccessMultipleAttempt','Overshoot_nbr','SuccessOvershoot_nbr','SuccessOvershoot'};

%fhgmdfghqmfghqù
for d=1:length(dates)
    DOI=dates(d);
    date_xls=replace(dates{d},'.','-');
    date_xls=insertAfter(date_xls,6,'20');
    date_backward=[date_xls(end-3:end) date_xls(end-6:end-5) date_xls(end-9:end-8)];
    videocod_file=fullfile(output_path, ['motor_rake_' date_backward '_' date_xls '_' coder '.xlsx']);
    
    videotable=readtable(videocod_file);
    
    validTrials=find(videotable.ValidVideo==1);
    validTrials_nbr=length(validTrials);
    thirds=floor(validTrials_nbr/3);
    modulo=mod(validTrials_nbr,3);
    onethird_idx=validTrials(1:thirds);
    twothird_idx=validTrials(thirds+1:2*thirds+modulo);
    threethird_idx=validTrials(2*thirds+modulo+1:3*thirds+modulo);
    
    Success=find(videotable.Success==1);
    Success_nbr=length(Success);
    Success_rate=(Success_nbr/validTrials_nbr)*100;
    
    Success_oneT_nbr=length(find(videotable.Success(onethird_idx)==1));
    Success_twoT_nbr=length(find(videotable.Success(twothird_idx)==1));
    Success_threeT_nbr=length(find(videotable.Success(threethird_idx)==1));
    Success_oneT_rate=(Success_oneT_nbr/thirds)*100;
    Success_twoT_rate=(Success_twoT_nbr/(thirds+modulo))*100;
    Success_threeT_rate=(Success_threeT_nbr/thirds)*100;
    
    Success_day_oneT_rate=(Success_oneT_nbr/validTrials_nbr)*100;
    Success_day_twoT_rate=(Success_twoT_nbr/validTrials_nbr)*100;
    Success_day_threeT_rate=(Success_threeT_nbr/validTrials_nbr)*100;
    
    conditionLeft_idx=find(strcmp(videotable.TargetStarting,'b'));
    conditionLeft_nbr=length(conditionLeft_idx);
    Success_left_nbr=length(find(videotable.Success(conditionLeft_idx)==1));
    Success_left_rate=(Success_left_nbr/conditionLeft_nbr)*100;
    Success_day_left_rate=(Success_left_nbr/validTrials_nbr)*100;
    
    conditionCenter_idx=find(strcmp(videotable.TargetStarting,'c'));
    conditionCenter_nbr=length(conditionCenter_idx);
    Success_Center_nbr=length(find(videotable.Success(conditionCenter_idx)==1));
    Success_Center_rate=(Success_Center_nbr/conditionCenter_nbr)*100;
    Success_day_center_rate=(Success_Center_nbr/validTrials_nbr)*100;
    
    conditionRight_idx=find(strcmp(videotable.TargetStarting,'d'));
    conditionRight_nbr=length(conditionRight_idx);
    Success_Right_nbr=length(find(videotable.Success(conditionRight_idx)==1));
    Success_Right_rate=(Success_Right_nbr/conditionRight_nbr)*100;
    Success_day_right_rate=(Success_Right_nbr/validTrials_nbr)*100;
    
     alignedTrial_idx=find((videotable.RakeStarting==15 & strcmp(videotable.TargetStarting,'b')) | ...
         (videotable.RakeStarting==17 & strcmp(videotable.TargetStarting,'c')) | ...
         (videotable.RakeStarting==19 & strcmp(videotable.TargetStarting,'d')));
     alignedTrial_nbr=length(alignedTrial_idx);
     SuccessAligned_nbr=length(find(videotable.Success(alignedTrial_idx)==1));
     SuccessAligned_rate=(SuccessAligned_nbr/alignedTrial_nbr)*100;
     Success_day_Aligned_rate=(SuccessAligned_nbr/validTrials_nbr)*100;
     
     Right2left=((strcmp(videotable.TargetStarting,'b')&(videotable.RakeStarting==16|videotable.RakeStarting==17|...
    videotable.RakeStarting==18|videotable.RakeStarting==19|videotable.RakeStarting==20|videotable.RakeStarting==21|...
    videotable.RakeStarting==22|videotable.RakeStarting==5|videotable.RakeStarting==6|videotable.RakeStarting==7|...
    videotable.RakeStarting==8|videotable.RakeStarting==9|videotable.RakeStarting==10|videotable.RakeStarting==11))|...
    (strcmp(videotable.TargetStarting,'c')&(videotable.RakeStarting==18|videotable.RakeStarting==19|...
    videotable.RakeStarting==20|videotable.RakeStarting==21|videotable.RakeStarting==22|videotable.RakeStarting==7|...
    videotable.RakeStarting==8|videotable.RakeStarting==9|videotable.RakeStarting==10|videotable.RakeStarting==11))|...
    (strcmp(videotable.TargetStarting,'d')&(videotable.RakeStarting==20|videotable.RakeStarting==21|...
    videotable.RakeStarting==22|videotable.RakeStarting==9|videotable.RakeStarting==10|videotable.RakeStarting==11)));

    Right2left_idx=find(Right2left);
    Right2left_nbr=length(Right2left_idx);
    SuccessR2L_nbr=length(find(videotable.Success(Right2left_idx)==1));
    SuccessR2L_rate=(SuccessR2L_nbr/Right2left_nbr)*100;
    Success_day_R2L_rate=(SuccessR2L_nbr/validTrials_nbr)*100;
    
    Left2right=((strcmp(videotable.TargetStarting,'d')&(videotable.RakeStarting==12|videotable.RakeStarting==13|...
    videotable.RakeStarting==14|videotable.RakeStarting==15|videotable.RakeStarting==16|videotable.RakeStarting==17|...
    videotable.RakeStarting==18|videotable.RakeStarting==1|videotable.RakeStarting==2|videotable.RakeStarting==3|...
    videotable.RakeStarting==4|videotable.RakeStarting==5|videotable.RakeStarting==6|videotable.RakeStarting==7))|...
    (strcmp(videotable.TargetStarting,'c')&(videotable.RakeStarting==12|videotable.RakeStarting==13|...
    videotable.RakeStarting==14|videotable.RakeStarting==15|videotable.RakeStarting==16|videotable.RakeStarting==1|...
    videotable.RakeStarting==2|videotable.RakeStarting==3|videotable.RakeStarting==4|videotable.RakeStarting==5))|...
    (strcmp(videotable.TargetStarting,'b')&(videotable.RakeStarting==12|videotable.RakeStarting==13|...
    videotable.RakeStarting==14|videotable.RakeStarting==1|videotable.RakeStarting==2|videotable.RakeStarting==3)));
    
    Left2right_idx=find(Left2right);
    Left2right_nbr=length(Left2right_idx);
    SuccessL2R_nbr=length(find(videotable.Success(Left2right_idx)==1));
    SuccessL2R_rate=(SuccessL2R_nbr/Left2right_nbr)*100;
    Success_day_L2R_rate=(SuccessL2R_nbr/validTrials_nbr)*100;

    MultipleAttempts_idx=find(videotable.MultipleAttempts==1);
    MultipleAttempts_nbr=length(MultipleAttempts_idx);
    Success_MultipleAttempts_nbr=length(find(videotable.Success(MultipleAttempts_idx)==1));
    Success_MultipleAttempts_rate=(Success_MultipleAttempts_nbr/MultipleAttempts_nbr)*100;
    Success_day_MultipleAttempts_rate=(Success_MultipleAttempts_nbr/validTrials_nbr)*100;
    
    Overshoot_idx=find(videotable.Overshoot==1);
    Overshoot_nbr=length(Overshoot_idx);
    Success_Overshoot_nbr=length(find(videotable.Success(Overshoot_idx)==1));
    Success_Overshoot_rate=(Success_Overshoot_nbr/Overshoot_nbr)*100;
    Success_day_Overshoot_rate=(Success_Overshoot_nbr/validTrials_nbr)*100;
    
    Behavior(d,:)={DOI,validTrials_nbr,conditionLeft_nbr,conditionCenter_nbr,conditionRight_nbr,...
        Success_nbr,Success_rate,thirds,modulo,Success_oneT_nbr,Success_twoT_nbr,Success_threeT_nbr,...
        Success_oneT_rate,Success_twoT_rate,Success_threeT_rate,Success_day_oneT_rate,Success_day_twoT_rate,...
        Success_day_threeT_rate,Success_left_nbr,Success_left_rate,Success_Center_nbr,Success_Center_rate,...
        Success_Right_nbr,Success_Right_rate,Success_day_left_rate,Success_day_center_rate,...
        Success_day_right_rate,alignedTrial_nbr,SuccessAligned_rate,Success_day_Aligned_rate,Right2left_nbr,...
        SuccessR2L_rate,Success_day_R2L_rate,Left2right_nbr,SuccessL2R_rate,Success_day_L2R_rate,...
       MultipleAttempts_nbr,Success_MultipleAttempts_nbr,Success_MultipleAttempts_rate,Overshoot_nbr,...
       Success_Overshoot_nbr,Success_Overshoot_rate};
end


% Right2left=((strcmp(videotable.TargetStarting,'b')&(videotable.RakeStarting==16|videotable.RakeStarting==17|...
%     videotable.RakeStarting==18|videotable.RakeStarting==19|videotable.RakeStarting==20|videotable.RakeStarting==21|...
%     videotable.RakeStarting==22|videotable.RakeStarting==5|videotable.RakeStarting==6|videotable.RakeStarting==7|...
%     videotable.RakeStarting==8|videotable.RakeStarting==9|videotable.RakeStarting==10|videotable.RakeStarting==11))|...
%     (strcmp(videotable.TargetStarting,'c')&(videotable.RakeStarting==18|videotable.RakeStarting==19|...
%     videotable.RakeStarting==20|videotable.RakeStarting==21|videotable.RakeStarting==22|videotable.RakeStarting==7|...
%     videotable.RakeStarting==8|videotable.RakeStarting==9|videotable.RakeStarting==10|videotable.RakeStarting==11))|...
%     (strcmp(videotable.TargetStarting,'d')&(videotable.RakeStarting==20|videotable.RakeStarting==21|...
%     videotable.RakeStarting==22|videotable.RakeStarting==9|videotable.RakeStarting==10|videotable.RakeStarting==11)));
% Right2left_idx=find(Right2left);
% 
% Left2right=((strcmp(videotable.TargetStarting,'d')&(videotable.RakeStarting==12|videotable.RakeStarting==13|...
%     videotable.RakeStarting==14|videotable.RakeStarting==15|videotable.RakeStarting==16|videotable.RakeStarting==17|...
%     videotable.RakeStarting==18|videotable.RakeStarting==1|videotable.RakeStarting==2|videotable.RakeStarting==3|...
%     videotable.RakeStarting==4|videotable.RakeStarting==5|videotable.RakeStarting==6|videotable.RakeStarting==7))|...
%     (strcmp(videotable.TargetStarting,'c')&(videotable.RakeStarting==12|videotable.RakeStarting==13|...
%     videotable.RakeStarting==14|videotable.RakeStarting==15|videotable.RakeStarting==16|videotable.RakeStarting==1|...
%     videotable.RakeStarting==2|videotable.RakeStarting==3|videotable.RakeStarting==4|videotable.RakeStarting==5))|...
%     (strcmp(videotable.TargetStarting,'b')&(videotable.RakeStarting==12|videotable.RakeStarting==13|...
%     videotable.RakeStarting==14|videotable.RakeStarting==1|videotable.RakeStarting==2|videotable.RakeStarting==3)));
% Left2right_idx=find(Left2right);

%save table in output directory