function AT_trial_idx=rakecod(removed_trials)

%AlignedTrials_idx=rakecod(data, dates)

%date format 'dd-mm-yyyy'

% date_data={};
% for i=1:length(dates)
    %videocod_file=fullfile(C:\Users\kirchher\project\video_coding\,sprintf('fr_b_%s_%s_whole_trial.mat',array,dates{i})));
    videocod_file = 'C:\Users\kirchher\project\video_coding\table\VideoCoding_May\motor_rake_20190515_15-05-2019_SK.xlsx';
    videocod = readtable(videocod_file);

% PerfectTrials = videocod.ValidVideo==1 & ...
%                 videocod.DoesTheTask==1 & ...
%                 videocod.Success==1 & ...
%                 videocod.MoveTowardTarget==1 & ...
%                 videocod.RakePulled==1 & ...
%                 videocod.Groove_graspPriority==1 &...
%                 videocod.MultipleAttempts==0 & ...
%                 videocod.PlaceTarget==0 & ...
%                 videocod.ShaftCorrection==0 & ...
%                 videocod.MissTarget==0 & ...
%                 videocod.HitTarget==0 & ...
%                 videocod.Volte==0 & ...
%                 videocod.ExpInterv==0 & ...
%                 videocod.RakeGuidance==0 & ...
%                 videocod.RakeOnlyTouchedOrGrasped==0 & ...
%                 ~strcmp(videocod.RakeStarting,'17');

% SterotypedPull = videocod.ValidTrial==1 & ...
%                 videocod.Success==0 & ...
%                 videocod.MoveTowardTarget==0 & ...
%                 videocod.StereotypedPulling==1 & ...
%                 videocod.MultipleAttempts==0 & ...
%                 videocod.PlaceTarget==0 & ...
%                 videocod.ShaftCorrection==0 & ...
%                 videocod.MissTarget==0 & ...
%                 videocod.ExpInterv==0 & ...
%                 videocod.RakeGuidance==0 & ...
%                 videocod.RakeOnlyTouchedOrGrasped==0 ; %& ...
               
            
%             strcmp(videocod.HitTarget,'0') & ...
%                 strcmp(videocod.Volte,'0') & ...
%                  strcmp(videocod.TargetStarting,'b');
            
% AlignedTrial = videocod.ValidTrial==1 & ...
%                 videocod.DoesTheTask==1 & ...
%                 videocod.Success==1 & ...
%                 videocod.MoveTowardTarget==0 & ...
%                 videocod.RakePulled==1 & ...
%                 videocod.MultipleAttempts==0 & ...
%                 videocod.ShaftCorrection==0 & ...
%                 videocod.MissTarget==0 & ...
%                 strcmp(videocod.HitTarget,'0') & ...
%                 strcmp(videocod.Volte,'0') & ...
%                 videocod.ExpInterv==0 & ...
%                 videocod.RakeGuidance==0 & ...
%                 videocod.RakeOnlyTouchedOrGrasped==0 & ...
%                 videocod.TouchRakeHead==0 & ...
%                 videocod.PulledInSteps==0 & ...
%                 videocod.ShaftCorrection==0 & ...
%                 strcmp(videocod.ReleaseTheRake,'0') & ...
%                 strcmp(videocod.SpasmHandle,'0');
            
AlignedTrial = videocod.ValidTrial==1 & ...
                videocod.DoesTheTask==1 & ...
                videocod.Success==1 & ...
                videocod.MoveTowardTarget==0 & ...
                videocod.RakePulled==1 & ...
                videocod.MultipleAttempts==0 & ...
                videocod.ShaftCorrection==0 & ...
                videocod.MissTarget==0 & ...
                videocod.ExpInterv==0 & ...
                videocod.RakeGuidance==0 & ...
                videocod.RakeOnlyTouchedOrGrasped==0 & ...
                videocod.TouchRakeHead==0 & ...
                videocod.PulledInSteps==0 & ...
                videocod.ShaftCorrection==0;

            
% PerfectTrials_idx = find(PerfectTrials);
%SterotypedPull_idx = find(SterotypedPull);
AlignedTrial_idx = find(AlignedTrial);

%PerfectTrials_list = videocod.Date(PerfectTrials_idx);
%SterotypedPull_list = videocod.Date(SterotypedPull_idx);
AlignedTrial_list = videocod.Date(AlignedTrial_idx);

for i=1:length(AlignedTrial_list)
    ATofinterest=AlignedTrial_list(i);
    ATcropped=ATofinterest{1,1}(10:end);
    AlignedTrial_list{i}=ATcropped;
end

trial_info_file = 'E:\project\tool_learning\data\preprocessed_data\betta\15.05.19\trial_info.csv';
trial_info = readtable(trial_info_file, 'readVariableNames', true, 'delimiter','comma');
trial_info=trial_info(find(strcmp(trial_info.status,'good')),:);
trial_info=trial_info(setdiff(1:nrows(trial_info),removed_trials),:);

%trial_info=trial_info(setdiff(1:nrow(trial_info)),
% List of trial indices (for videos mapped to a good trial)
AT_trial_idx=[];
for i=1:length(AlignedTrial_list)
    % Find trial for this video
    AT_Trial=find(strcmp(trial_info.video, AlignedTrial_list{i}));
    % If trial found and it's good - add to list
    if length(AT_Trial)>0 && strcmp(trial_info.task{AT_Trial},'motor_task_rake')
        AT_trial_idx(end+1)=AT_Trial;
    end
end
