function [T,X,Y]=eventide_gaze_filter(event_channels,tsevs,x,y,sf,nstd)
n=max(size(event_channels));
T=cell(n,1);
X=cell(n,1);
Y=cell(n,1);
mex=cell(n,1);
mey=cell(n,1);
% mst=cell(n,1);
mstx=cell(n,1);
msty=cell(n,1);
mask=cell(n,1);
for i=1:n
    T{i}=int32(tsevs{event_channels(i)}*sf);
%     m=size(T{i},1);
    X{i}=x(T{i});
    Y{i}=y(T{i});
%     mex{i}=mean(X{i});
%     mey{i}=mean(Y{i});
    mex{i}=median(X{i});
    mey{i}=median(Y{i});
    mstx{i}=std(X{i},0)/sqrt(size(X{i},1));
    msty{i}=std(Y{i},0)/sqrt(size(Y{i},1));
    mask{i}=((X{i}>mex{i}-nstd*mstx{i} & X{i}<mex{i}+nstd*mstx{i}) & (Y{i}>mey{i}-nstd*msty{i} & Y{i}<mey{i}+nstd*msty{i}));
    Xp=[X{i}];
    Yp=[Y{i}];
%     Xp=sort([X{i}]);
%     Yp=sort([Y{i}]);
%     mst{i}=(1.96*sqrt(m)/2);
%     mask{i}=(X{i}>Xp(int32(m/2-mst{i})) & X{i}<Xp(int32(m/2+mst{i}))...
%         & (Y{i}>Yp(int32(m/2-mst{i})) & Y{i}<Yp(int32(m/2+mst{i}))));
    X{i}=Xp(mask{i});
    Y{i}=Yp(mask{i});
end
